/**
 * Square Payments Integration Helper
 * Supports Cloudflare Workers (platform.env) and local Node/Vite environments.
 */

export interface SquareConfig {
	applicationId: string;
	accessToken: string;
	locationId: string;
	isSandbox: boolean;
	isConfigured: boolean;
	baseUrl: string;
	sdkUrl: string;
}

export function getSquareConfig(platform?: App.Platform): SquareConfig {
	const appId =
		platform?.env?.SQUARE_APPLICATION_ID ||
		(typeof process !== 'undefined' ? process.env?.SQUARE_APPLICATION_ID || process.env?.VITE_SQUARE_APPLICATION_ID : '') ||
		'';

	const accessToken =
		platform?.env?.SQUARE_ACCESS_TOKEN ||
		(typeof process !== 'undefined' ? process.env?.SQUARE_ACCESS_TOKEN : '') ||
		'';

	const locationId =
		platform?.env?.SQUARE_LOCATION_ID ||
		(typeof process !== 'undefined' ? process.env?.SQUARE_LOCATION_ID : '') ||
		'';

	const envSetting =
		platform?.env?.SQUARE_ENVIRONMENT ||
		(typeof process !== 'undefined' ? process.env?.SQUARE_ENVIRONMENT : '');

	const isSandbox =
		envSetting === 'sandbox' ||
		appId.startsWith('sandbox-') ||
		accessToken.startsWith('EAAA');

	const baseUrl = isSandbox
		? 'https://connect.squareupsandbox.com'
		: 'https://connect.squareup.com';

	const sdkUrl = isSandbox
		? 'https://sandbox.web.squarecdn.com/v1/square.js'
		: 'https://web.squarecdn.com/v1/square.js';

	return {
		applicationId: appId,
		accessToken,
		locationId,
		isSandbox,
		isConfigured: Boolean(appId && accessToken),
		baseUrl,
		sdkUrl
	};
}

/**
 * Fetches the merchant's first active location if locationId is not explicitly configured.
 */
async function getOrFetchLocationId(config: SquareConfig): Promise<string> {
	if (config.locationId) {
		return config.locationId;
	}

	try {
		const response = await fetch(`${config.baseUrl}/v2/locations`, {
			method: 'GET',
			headers: {
				'Square-Version': '2024-10-16',
				Authorization: `Bearer ${config.accessToken}`,
				'Content-Type': 'application/json'
			}
		});

		if (!response.ok) {
			const errData = await response.json().catch(() => ({}));
			console.error('Failed to fetch Square locations:', errData);
			throw new Error('Could not retrieve merchant location from Square.');
		}

		const data = await response.json();
		const activeLocation = data.locations?.find((loc: any) => loc.status === 'ACTIVE') || data.locations?.[0];
		if (!activeLocation?.id) {
			throw new Error('No active location found on your Square merchant account.');
		}

		return activeLocation.id;
	} catch (err: any) {
		console.error('Error fetching Square location:', err);
		throw new Error(err.message || 'Failed to detect Square location.');
	}
}

export interface ProcessPaymentParams {
	platform?: App.Platform;
	sourceId: string;
	amountCAD: number;
	donorName: string;
	email?: string;
	message?: string;
	idempotencyKey?: string;
}

export interface PaymentResult {
	success: boolean;
	paymentId: string;
	status: string;
	receiptUrl?: string;
	amount: number;
	currency: string;
}

/**
 * Charges the payment token generated by the Square Web Payments SDK.
 */
export async function processSquarePayment(params: ProcessPaymentParams): Promise<PaymentResult> {
	const config = getSquareConfig(params.platform);

	if (!config.isConfigured) {
		throw new Error(
			'Square payment credentials are not configured. Please set SQUARE_APPLICATION_ID and SQUARE_ACCESS_TOKEN.'
		);
	}

	const locationId = await getOrFetchLocationId(config);
	const amountInCents = Math.round(params.amountCAD * 100);

	if (amountInCents <= 0) {
		throw new Error('Payment amount must be greater than $0 CAD.');
	}

	const idempotencyKey = params.idempotencyKey || `don_${crypto.randomUUID()}`;

	const requestBody = {
		source_id: params.sourceId,
		idempotency_key: idempotencyKey,
		amount_money: {
			amount: amountInCents,
			currency: 'CAD'
		},
		location_id: locationId,
		buyer_email_address: params.email || undefined,
		note: `Nepal Flood Relief: ${params.donorName}${params.message ? ' - ' + params.message : ''}`.slice(0, 500)
	};

	const response = await fetch(`${config.baseUrl}/v2/payments`, {
		method: 'POST',
		headers: {
			'Square-Version': '2024-10-16',
			Authorization: `Bearer ${config.accessToken}`,
			'Content-Type': 'application/json'
		},
		body: JSON.stringify(requestBody)
	});

	const resData = await response.json().catch(() => ({}));

	if (!response.ok || resData.errors) {
		const firstError = resData.errors?.[0];
		const errorMsg =
			firstError?.detail ||
			firstError?.code ||
			`Payment processing failed with status ${response.status}.`;
		console.error('Square Payment API error:', resData);
		throw new Error(errorMsg);
	}

	const payment = resData.payment;
	if (!payment) {
		throw new Error('No payment details returned by Square API.');
	}

	return {
		success: true,
		paymentId: payment.id,
		status: payment.status,
		receiptUrl: payment.receipt_url || undefined,
		amount: Number(payment.amount_money.amount) / 100,
		currency: payment.amount_money.currency
	};
}
